
export const FETCH_BUDGET='FETCH_BUDGET';
export const NEW_BUDGET='NEW_BUDGET';
export const EDIT_BUDGET='EDIT_BUDGET';
export const DELETE_BUDGET='DELETE_BUDGET';

export const FETCH_TRANSACTION='FETCH_TRANSACTION';
export const NEW_TRANSACTION='NEW_TRANSACTION';
export const EDIT_TRANSACTION='EDIT_TRANSACTION';
export const DELETE_TRANSACTION='DELETE_TRANSACTION';

export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const LOGIN_USER_FAIL="LOGIN_USER_FAIL";
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL";
export const LOGOUT_REQUEST="LOGOUT_REQUEST";

